version: '3' # specify docker-compose version

# Define the services/containers to be run
services:
  express: #name of the second service
    build: 
      context: ./src-api/backend-HernandezTruck # specify the directory of the Dockerfile
      dockerfile: Dockerfile
    ports:
      - "3000:3000" #specify ports forewarding

  angular:
    hostname: localhost
    #container_name: angular-app
    build:     
      context: ./src-frontend/frontend-HernandezTruck
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - express
